const campaigns = {
  2025: [
    {
      title: "Ramadan 2025",
      description:
        "Distribute iftar meals and essential aid during Ramadan 2025.",
      images: [
        "/images/Ramadan2025/Ramadan1.jpg",
        "/images/Ramadan2025/Ramadan2.jpg",
        "/images/Ramadan2025/Ramadan3.jpg",
        "/images/Ramadan2025/Ramadan4.jpg",
        "/images/Ramadan2025/Ramadan5.jpg",
        "/images/Ramadan2025/Ramadan6.jpg",
        "/images/Ramadan2025/Ramadan7.jpg",
        "/images/Ramadan2025/Ramadan8.jpg",
        "/images/Ramadan2025/Ramadan9.jpg",
        "/images/Ramadan2025/Ramadan10.jpg",
        "/images/Ramadan2025/Ramadan11.jpg",
        "/images/Ramadan2025/Ramadan12.jpg",
        "/images/Ramadan2025/Ramadan13.jpg",
        "/images/Ramadan2025/Ramadan14.jpg",
        "/images/Ramadan2025/Ramadan15.jpg",
        "/images/Ramadan2025/Ramadan16.jpg",
        "/images/Ramadan2025/Ramadan17.jpg",
        "/images/Ramadan2025/Ramadan18.jpg",
        "/images/Ramadan2025/Ramadan19.jpg",
        "/images/Ramadan2025/Ramadan20.jpg",
        "/images/Ramadan2025/Ramadan21.jpg",
        "/images/Ramadan2025/Ramadan22.jpg",
        "/images/Ramadan2025/Ramadan23.jpg",
        "/images/Ramadan2025/Ramadan24.jpg",
        "/images/Ramadan2025/Ramadan25.jpg",
        "/images/Ramadan2025/Ramadan26.jpg",
        "/images/Ramadan2025/Ramadan27.jpg",
        "/images/Ramadan2025/Ramadan28.jpg",
        "/images/Ramadan2025/Ramadan29.jpg",
        "/images/Ramadan2025/Ramadan30.jpg",
        "/images/Ramadan2025/Ramadan31.jpg",
        "/images/Ramadan2025/Ramadan32.jpg",
        "/images/Ramadan2025/Ramadan33.jpg",
        "/images/Ramadan2025/Ramadan34.jpg",
        "/images/Ramadan2025/Ramadan35.jpg",
        "/images/Ramadan2025/Ramadan36.jpg",
        "/images/Ramadan2025/Ramadan37.jpg",
        "/images/Ramadan2025/Ramadan38.jpg",
        "/images/Ramadan2025/Ramadan39.jpg",
        "/images/Ramadan2025/Ramadan40.jpg",
        "/images/Ramadan2025/Ramadan41.jpg",
        "/images/Ramadan2025/Ramadan42.jpg",
        "/images/Ramadan2025/Ramadan43.jpg",
        "/images/Ramadan2025/Ramadan44.jpg",
        "/images/Ramadan2025/Ramadan45.jpg",
        "/images/Ramadan2025/Ramadan46.jpg",
        "/images/Ramadan2025/Ramadan47.jpg",
      ],
    },
    {
      title: "Water For Gaza",
      description:
        "Provide access to clean drinking water for Gaza communities.",
      images: [
        "/images/Water2025/water1.jpg",
        "/images/Water2025/water2.jpg",
        "/images/Water2025/water3.jpg",
        "/images/Water2025/water4.jpg",
        "/images/Water2025/water5.jpg",
        "/images/Water2025/water6.jpg",
        "/images/Water2025/water7.jpg",
        "/images/Water2025/water8.jpg",
        "/images/Water2025/water9.jpg",
        "/images/Water2025/water10.jpg",
        "/images/Water2025/water11.jpg",
        "/images/Water2025/water12.jpg",
        "/images/Water2025/water13.jpg",
        "/images/Water2025/water14.jpg",
        "/images/Water2025/water15.jpg",
        "/images/Water2025/water16.jpg",
        "/images/Water2025/water17.jpg",
        "/images/Water2025/water18.jpg",
        "/images/Water2025/water19.jpg",
        "/images/Water2025/water20.jpg",
        "/images/Water2025/water21.jpg",
        "/images/Water2025/water22.jpg",
        "/images/Water2025/water23.jpg",
        "/images/Water2025/water24.jpg",
        "/images/Water2025/water25.jpg",
        "/images/Water2025/water26.jpg",
        "/images/Water2025/water27.jpg",
        "/images/Water2025/water28.jpg",
        "/images/Water2025/water29.jpg",
        "/images/Water2025/water30.jpg",
        "/images/Water2025/water31.jpg",
        "/images/Water2025/water32.jpg",
        "/images/Water2025/water33.jpg",
        "/images/Water2025/water34.jpg",
        "/images/Water2025/water35.jpg",
        "/images/Water2025/water36.jpg",
        "/images/Water2025/water37.jpg",
        "/images/Water2025/water38.jpg",
        "/images/Water2025/water39.jpg",
        "/images/Water2025/water40.jpg",
        "/images/Water2025/water41.jpg",
        "/images/Water2025/water42.jpg",
        "/images/Water2025/water43.jpg",
      ],
    },
    {
      title: "SOS Gaza",
      description: "Emergency humanitarian aid and relief for Gaza residents.",
      images: [
        "/images/SOS2025/clothes1.jpg",
        "/images/SOS2025/clothes2.jpg",
        "/images/SOS2025/clothes3.jpg",
        "/images/SOS2025/clothes4.jpg",
        "/images/SOS2025/clothes5.jpg",
        "/images/SOS2025/clothes6.jpg",
        "/images/SOS2025/clothes7.jpg",
        "/images/SOS2025/clothes8.jpg",
        "/images/SOS2025/clothes9.jpg",
        "/images/SOS2025/clothes10.jpg",
        "/images/SOS2025/clothes11.jpg",
        "/images/SOS2025/clothes12.jpg",
        "/images/SOS2025/clothes13.jpg",
        "/images/SOS2025/clothes14.jpg",
        "/images/SOS2025/clothes15.jpg",
        "/images/SOS2025/clothes16.jpg",
        "/images/SOS2025/clothes17.jpg",
        "/images/SOS2025/clothes18.jpg",
        "/images/SOS2025/clothes19.jpg",
        "/images/SOS2025/clothes20.jpg",
        "/images/SOS2025/clothes21.jpg",
        "/images/SOS2025/clothes22.jpg",
        "/images/SOS2025/clothes23.jpg",
        "/images/SOS2025/clothes24.jpg",
        "/images/SOS2025/clothes25.jpg",
        "/images/SOS2025/clothes26.jpg",
        "/images/SOS2025/clothes27.jpg",
        "/images/SOS2025/clothes28.jpg",
        "/images/SOS2025/clothes29.jpg",
        "/images/SOS2025/clothes30.jpg",
        "/images/SOS2025/clothes31.jpg",
        "/images/SOS2025/clothes32.jpg",
        "/images/SOS2025/clothes33.jpg",
        "/images/SOS2025/clothes34.jpg",
        "/images/SOS2025/clothes35.jpg",
      ],
    },
    {
      title: "Zakat Al Maal",
      description:
        "Fulfill your annual Zakat obligation and help those in need.",
      images: ["/images/ZakatAlMal/ZakatAlMal1.jpg"],
    },
    {
      title: "Orphan Sponsorship",
      description:
        "Sponsor an orphan and secure their future with your support.",
      images: [
        "/images/Orphan/Orphan1.jpg",
        "/images/Orphan/Orphan2.jpg",
        "/images/Orphan/Orphan3.jpg",
        "/images/Orphan/Orphan4.jpg",
        "/images/Orphan/Orphan5.jpg",
        "/images/Orphan/Orphan6.jpg",
      ],
    },
    {
      title: "Rafah Emergency",
      description: "Support families affected by the crisis in Rafah.",
      images: [
        "/images/RafahEmergency/RafahEmergency1.jpg",
        "/images/RafahEmergency/RafahEmergency2.jpg",
        "/images/RafahEmergency/RafahEmergency3.jpg",
        "/images/RafahEmergency/RafahEmergency4.jpg",
        "/images/RafahEmergency/RafahEmergency5.jpg",
        "/images/RafahEmergency/RafahEmergency6.jpg",
        "/images/RafahEmergency/RafahEmergency7.jpg",
        "/images/RafahEmergency/RafahEmergency8.jpg",
        "/images/RafahEmergency/RafahEmergency9.jpg",
        "/images/RafahEmergency/RafahEmergency10.jpg",
        "/images/RafahEmergency/RafahEmergency11.jpg",
        "/images/RafahEmergency/RafahEmergency12.jpg",
        "/images/RafahEmergency/RafahEmergency13.jpg",
        "/images/RafahEmergency/RafahEmergency14.jpg",
        "/images/RafahEmergency/RafahEmergency15.jpg",
        "/images/RafahEmergency/RafahEmergency16.jpg",
        "/images/RafahEmergency/RafahEmergency17.jpg",
        "/images/RafahEmergency/RafahEmergency18.jpg",
        "/images/RafahEmergency/RafahEmergency19.jpg",
        "/images/RafahEmergency/RafahEmergency20.jpg",
        "/images/RafahEmergency/RafahEmergency21.jpg",
        "/images/RafahEmergency/RafahEmergency22.jpg",
        "/images/RafahEmergency/RafahEmergency23.jpg",
        "/images/RafahEmergency/RafahEmergency24.jpg",
        "/images/RafahEmergency/RafahEmergency25.jpg",
        "/images/RafahEmergency/RafahEmergency26.jpg",
        "/images/RafahEmergency/RafahEmergency27.jpg",
        "/images/RafahEmergency/RafahEmergency28.jpg",
        "/images/RafahEmergency/RafahEmergency29.jpg",
        "/images/RafahEmergency/RafahEmergency30.jpg",
        "/images/RafahEmergency/RafahEmergency31.jpg",
        "/images/RafahEmergency/RafahEmergency32.jpg",
        "/images/RafahEmergency/RafahEmergency33.jpg",
        "/images/RafahEmergency/RafahEmergency34.jpg",
        "/images/RafahEmergency/RafahEmergency35.jpg",
        "/images/RafahEmergency/RafahEmergency36.jpg",
        "/images/RafahEmergency/RafahEmergency37.jpg",
        "/images/RafahEmergency/RafahEmergency38.jpg",
        "/images/RafahEmergency/RafahEmergency39.jpg",
        "/images/RafahEmergency/RafahEmergency40.jpg",
        "/images/RafahEmergency/RafahEmergency41.jpg",
        "/images/RafahEmergency/RafahEmergency42.jpg",
        "/images/RafahEmergency/RafahEmergency43.jpg",
        "/images/RafahEmergency/RafahEmergency44.jpg",
      ],
    },
    {
      title: "Ramadan Donations",
      description:
        "Support those in need this Ramadan and help secure a brighter future with your generous donation.",

      images: [
        "/images/RamadanDonations/RamadanDonation1.jpg",
        "/images/RamadanDonations/RamadanDonation2.jpg",
        "/images/RamadanDonations/RamadanDonation3.jpg",
        "/images/RamadanDonations/RamadanDonation4.jpg",
        "/images/RamadanDonations/RamadanDonation5.jpg",
        "/images/RamadanDonations/RamadanDonation6.jpg",
        "/images/RamadanDonations/RamadanDonation7.jpg",
        "/images/RamadanDonations/RamadanDonation8.jpg",
        "/images/RamadanDonations/RamadanDonation9.jpg",
        "/images/RamadanDonations/RamadanDonation10.jpg",
        "/images/RamadanDonations/RamadanDonation11.jpg",
        "/images/RamadanDonations/RamadanDonation12.jpg",
        "/images/RamadanDonations/RamadanDonation13.jpg",
        "/images/RamadanDonations/RamadanDonation14.jpg",
        "/images/RamadanDonations/RamadanDonation15.jpg",
        "/images/RamadanDonations/RamadanDonation16.jpg",
        "/images/RamadanDonations/RamadanDonation17.jpg",
        "/images/RamadanDonations/RamadanDonation18.jpg",
        "/images/RamadanDonations/RamadanDonation19.jpg",
        "/images/RamadanDonations/RamadanDonation20.jpg",
      ],
    },
  ],
  2024: [
    {
      title: "Orphan Sponsorship",
      description:
        "Sponsor an orphan and secure their future with your support.",
      images: [
        "/images/CardSlider/Donation1.jpg",
        "/images/CardSlider/Donation2.jpg",
        "/images/CardSlider/Donation3.jpg",
        "/images/CardSlider/Donation4.jpg",
        "/images/CardSlider/Donation5.jpg",
      ],
    },
  ],
};

export default campaigns;
